### PR TITLE
feature(flow): Add type checking to parameters

### PR DESCRIPTION
**Pull request by captainsafia**
Figured I shouldn't let this branch stall during finals and such. It can be merged and typing on other things can continue later.

### CODE REVIEW

**Comment by jdetle** [comment]
Ahh, the classic "I-dont-want-to-study-for-finals-so-here-is-a-PR", PR

**Comment by rgbkrk** [comment]
Hoorah! Thanks.

**Comment by lgeiger** [comment]
Thanks! 🎉 

(Pushed a commit to make Travis happy again)

**Comment by rgbkrk** [comment]
@captainsafia since things are passing would you want us to go ahead and merge it? We can then keep adding on afterward. There are some items we can make more explicit, they don't have to be part of this though.

**Comment by captainsafia** [comment]
Yes! Please go ahead and merge. I didn't want this to go stale on my local. There is definitely more to be done but I figure this small PR can get just jumpstarted towards typing this project.

**Comment by rgbkrk** [comment]
Thanks @captainsafia and @lgeiger!

**Pull request merged**
